# Generated by Django 6.0.3 on 2026-03-09 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['muscle_group', 'name']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Грудь'), ('back', 'Спина'), ('shoulders', 'Плечи'), ('biceps', 'Бицепс'), ('triceps', 'Трицепс'), ('legs', 'Ноги'), ('abs', 'Пресс'), ('cardio', 'Кардио'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Группа мышц'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Рабочий вес (кг)'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('current_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Текущий вес (кг)')),
                ('goal', models.CharField(blank=True, choices=[('mass', 'Набор массы'), ('cut', 'Похудение'), ('strength', 'Сила'), ('endurance', 'Выносливость')], default='mass', max_length=20, verbose_name='Цель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
