# Generated by Django 6.0.3 on 2026-03-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_aiadvicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('run', 'Бег'), ('cycling', 'Велосипед'), ('swimming', 'Плавание'), ('rowing', 'Гребля'), ('elliptical', 'Эллипсоид'), ('jump_rope', 'Скакалка'), ('walk', 'Ходьба'), ('hiit', 'Интервальная тренировка (HIIT)'), ('other', 'Другое')], default='run', max_length=20, verbose_name='Активность')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Дистанция (км)')),
                ('avg_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средний пульс (уд/мин)')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сжжено ккал')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_entries', to='fitness.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Кардио',
                'verbose_name_plural': 'Кардио-записи',
                'ordering': ['-workout__date'],
            },
        ),
    ]
