# Generated by Django 6.0.3 on 2026-03-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_cardioentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioentry',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Дистанция (км)'),
        ),
    ]
