# Generated by Django 6.0.3 on 2026-03-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_cardioentry_distance_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблон тренировки',
                'verbose_name_plural': 'Шаблоны тренировок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_count', models.PositiveIntegerField(default=3, verbose_name='Количество подходов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise', verbose_name='Упражнение')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workouttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Упражнение в шаблоне',
                'verbose_name_plural': 'Упражнения в шаблоне',
                'ordering': ['order'],
            },
        ),
    ]
