# Generated by Django 6.0.3 on 2026-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_workouttemplate_workouttemplateexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='is_bodyweight',
            field=models.BooleanField(default=False, verbose_name='Свой вес (Без отягощения)'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.CharField(help_text='Например: 10 или 10-8-8-6', max_length=50, verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Рабочий вес (кг)'),
        ),
    ]
