# Generated by Django 6.0.3 on 2026-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_workoutset_is_bodyweight_alter_workoutset_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.CharField(blank=True, help_text='Например: 60 или 60-65-70-75', max_length=50, null=True, verbose_name='Рабочий вес (кг)'),
        ),
    ]
