# Generated by Django 6.0.3 on 2026-03-12 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_workoutset_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioentry',
            name='avg_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)], verbose_name='Средний пульс (уд/мин)'),
        ),
        migrations.AlterField(
            model_name='cardioentry',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сжжено ккал'),
        ),
        migrations.AlterField(
            model_name='cardioentry',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дистанция (км)'),
        ),
        migrations.AlterField(
            model_name='cardioentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Текущий вес (кг)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Рост (см)'),
        ),
    ]
