# Generated by Django 6.0.3 on 2026-03-12 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_alter_cardioentry_avg_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Целевой вес (кг)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('later', 'Укажу позже'), ('mass', 'Набор массы'), ('cut', 'Похудение'), ('strength', 'Сила'), ('endurance', 'Выносливость'), ('health', 'Поддержание здоровья')], default='later', max_length=20, verbose_name='Цель'),
        ),
    ]
