# Generated by Django 6.0.3 on 2026-03-12 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_userprofile_avatar_userprofile_target_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(500)], verbose_name='Текущий вес (кг)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(500)], verbose_name='Целевой вес (кг)'),
        ),
        migrations.AlterField(
            model_name='workouttemplateexercise',
            name='sets_count',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Количество подходов'),
        ),
    ]
