# Generated by Django 6.0.3 on 2026-03-14 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_alter_workout_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Сидячий образ жизни (нет нагрузок)'), ('light', 'Малоактивный (1-3 тренировки в неделю)'), ('moderate', 'Умеренно активный (3-5 тренировок в неделю)'), ('very_active', 'Очень активный (интенсивные тренировки 6-7 раз в неделю)'), ('extra_active', 'Экстра-активный (физическая работа + тяжелые тренировки)')], default='light', max_length=20, verbose_name='Уровень активности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='AIStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(verbose_name='Калории')),
                ('protein', models.PositiveIntegerField(verbose_name='Белки (г)')),
                ('fats', models.PositiveIntegerField(verbose_name='Жиры (г)')),
                ('carbs', models.PositiveIntegerField(verbose_name='Углеводы (г)')),
                ('diet_plan', models.TextField(verbose_name='План питания')),
                ('workout_strategy', models.TextField(verbose_name='Стратегия тренировок')),
                ('date_generated', models.DateTimeField(auto_now=True, verbose_name='Дата генерации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_strategy', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ИИ Стратегия',
                'verbose_name_plural': 'ИИ Стратегии',
            },
        ),
    ]
