# Generated by Django 6.0.3 on 2026-03-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dashboard_layout',
            field=models.JSONField(blank=True, null=True, verbose_name='Расположение виджетов на дашборде'),
        ),
    ]
