# Generated by Django 6.0.3 on 2026-03-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_userprofile_dashboard_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='Раскладка дашборда'),
        ),
    ]
