# Generated by Django 6.0.3 on 2026-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_alter_userprofile_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dismissed_plateau_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия уведомления о плато'),
        ),
    ]
