# Generated by Django 6.0.3 on 2026-03-15 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_userprofile_dismissed_plateau_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='body_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес тела'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
